### ISSUE TITLE
Polish 3

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/rick-and-morty-character-viewer#16]
## ✅ Task List

> ##### Commit checklist for tasks needed.

- [x] Apply border radius on character cards
- [x] Set image overflow hidden on character card
- [x] Apply horizontal padding to character card text
- [x] Resove bug when heart icon is clicked
